### ISSUE TITLE
Add the figure directive

### ISSUE THREAD

**Issue by Gregwar** [Gregwar/RST#10]

**Comment by KSSonline** [comment]
Hi is there any chance to see this directive in the near future?

**Comment by Gregwar** [comment]
Hello,
I think this is can easily done, since the `image` directive already exists and is quite similar (expected the legend)

**Comment by Gregwar** [comment]
Maybe you can be more accurate about your use case and provide some examples of what you needs?

**Comment by KSSonline** [comment]
I'm parsing several .rst files and some do have e.g. 
`.. figure:: Documentation/Sample/dfeyer-donpark.png`
like this package at the bottom (https://github.com/ttreeagency/Ttree.Identicons/blob/master/README.rst) . It would be also okay if not defined markups wouldn't throw an error and just print it as plain text.

**Comment by Gregwar** [comment]
You can try this if you want to avoid crashing on unknown directives:

```php
<?php
$parser->getEnvironment()->getErrorManager()->abortOnError(false);
```

**Comment by KSSonline** [comment]
Awesome, this helps a lot! Thank you very much!

**Comment by Gregwar** [comment]
Made a simple implementation in f40ef36

**Comment by KSSonline** [comment]
Wow! Thank you very much!
