### ISSUE TITLE
Directive example?

### ISSUE THREAD

**Issue by dolfinitylearning** [Gregwar/RST#27]
Thnx for RST!

I can't figure out how to write a directive. Directive code:

```
class Dog extends Directive
{
    public function getName()
    {
        return 'dog';
    }

    public function processNode(Parser $parser, $variable, $data, array $options)
    {
        return new Nodes\ParagraphNode('<b>'.$data.'</b>');
    }
}
```

Calling code:

```
class Thing extends Gregwar\RST\Parser {
  protected $dog;
  function __construct() {
    parent::__construct();
    $this->dog = new Dog;
    $this->registerDirective($this->dog);
  }
}

$parser = new Thing(); 
$rst = ' 
Hello world
===========

.. dog:: nothing
    :scale: 50
    :weight: 68

    This is a dog.

That was a dog.
';

// Parse it
$document = $parser->parse($rst);

// Render it
echo $document;

```

`processNode` in `Dog` gets the word "nothing" in the param $data. $variable is empty. $options is as expected. `processNode` doesn't seem to get the body (This is a dog).

What am I missing?

A tutorial would be useful. I'm willing to write one if I can figure out what's going on.

**Comment by Gregwar** [comment]
Ok, I must confess directives are a little tricky to write.  This is normal that your method doesn't get the body, `$data` here is the string that follows the `::`.

Can you tell more about what your use case? What do you want to do?

Do you want your directive to get some code (text that is not parsed as RST, like code blocks does to highlight embedded code) or to get a sub document (text that is parsed as RST, like div block does to wrap nodes in a `<div>`)?

**Comment by dolfinitylearning** [comment]
Thnx for the quick reply!

The use case is for writing textbook-like-things. Check out this page:

https://programming.cybercour.se/course/dudes-work

Students watch Klaus and Jeremy working on a program (scroll down that page a bit). Authors have a library of about eight different images of Klaus with different expressions; the same for Jeremy. What I'd like an author to be able to do is something like this (pseudent means pseudo-student):

.. pseudent:: klaus_neutral2

    Dude, let's start with the easy stuff. Typing the labels into the worksheet,
    and making the Convert button.

.. pseudent:: jeremy_smile1

    OK, no problem, dude… (clickity clickity typeity typeity)… there. 

That turns into a box on the page, with the appropriate image and text. (The UI would show the author an image rather than the tag klaus_neutral, but that's not a ReST problem.)

**Comment by Gregwar** [comment]
Ok, great

What you want to do is a SubDirective, which is a special case where everything below is parsed as a document

Actually, I think this can be done using the already existent div directive and some css

**Comment by dolfinitylearning** [comment]
Yeeehah! Works! And I can nest directives. Goodbye, Textile, time for some ReSTy fun.

Thanks!
Kieran
