### ISSUE TITLE
Question inline directive

### ISSUE THREAD

**Issue by FilipLukac** [Gregwar/RST#29]
Hello, could I make some inline directives ?:) something like

I write something and <this is my code> and I'm writting something new

I would like to get something like

```
I write something and <code> this is my code</code>
```

And I want it inline

**Comment by Gregwar** [comment]
I think the RST way to do this is using replaces, an example is:

```rst
Here is a foo: |foo|

.. |foo| image:: image/foo.png
    :width: 100
```

http://docutils.sourceforge.net/docs/ref/rst/directives.html#replacement-text

**Comment by FilipLukac** [comment]
@Gregwar thank you so much ! I appreciate it. And I have one more question,

Could I use `processSub(RST\Parser $parser, $document, $variable, $data, array $options)` 
I want to parse the `$data` variable trough the some some function to parse this variable.

I have something like:

```
.. task:: Something is over there and ``this is code``
    And this is another part ``another code``
```
I want to translate (parse) variable passed as argument of `task` directive, could I use pre-defined methods ? Or should I write my own methods to replace this `<code>` block.

`$data` variable always returns me plain text.

**Comment by Gregwar** [comment]
You might use the `Span` class:

̀```php
$this->span = $parser->createSpan($data);
```

Then, you can add this span to the document and it will be interpreted

**Comment by FilipLukac** [comment]
@Gregwar Your solution works like a charm. Thank you so much for such a quick response. 


```php
$parser->createSpan($str);
```
Works for me.
