### ISSUE TITLE
Why not parsed?

### ISSUE THREAD

**Issue by Lexus27** [Gregwar/RST#33]
I have this RST Code
```

Hello world
===========

```
But render is plaintext, in `<p>Hello world\r\n===========\r\n</p>`

I used example from README.md

```
$parser = new \Gregwar\RST\Parser;
$value = (string)$parser->parse($value);
```

Now I used the whole sample:
```

Hello world
===========

What is it?
----------
This is a **RST** document!

Where can I get it?
-------------------
You can get it on the `GitHub page <https://github.com/Gregwar/RST>`_

```

and what I see:

```
<p>Hello world
===========
</p>
<p>What is it?
----------
This is a <strong>RST</strong> document!
</p>
<p>Where can I get it?
-------------------
You can get it on the <a href="https://github.com/Gregwar/RST">GitHub page</a>
</p>
```

a link and bolder is right rendered, but heading is not correctly

**Comment by Lexus27** [comment]
I find reasons: <CRLF> not supported.
It is necessary to implement a forced substitution \ r \ n to \ n before analysis
`str_replace("\r\n","\n", $value);` before parse

**Comment by Gregwar** [comment]
Hello
Ok, would you mind creating a PR for this?

**Comment by Gregwar** [comment]
+ unit test ;-)

**Comment by Gregwar** [comment]
I fixed this

**Comment by Lexus27** [comment]
I could not do PR, because I have not changed Gregwar/RST core of my changes were outside, and you know better than the more efficient approach to internal architecture), why should I spoil your kernel with their crutches?)

**Comment by Gregwar** [comment]
No problem, it's done on master now
