### ISSUE TITLE
Wrong links for relative URLs, when starting with a forward slash

### ISSUE THREAD

**Issue by pacproduct** [Gregwar/RST#39]
I'm facing what I believe is an issue when using links with this RST library:
When generating links that begin with '/', the resulting output does not match what I would expect as the initial forward slash gets removed from the final HTML link.

Here is an example (using RST v1.0.4):

----

**Source code:**
```php
// Load RST parser.
$parser = new Parser();

// Parse input RST text.
$parsed_text = $parser->parse('
This is a link: `My link </my/path/to/link.html>`__
');
$result = $parsed_text->renderDocument();

// Output HTML result.
echo $result;
```
**Expected result:**
```html
<p>This is a link: <a href="/my/path/to/link.html">My link</a></p>
```

**Observed result:**
```html
<p>This is a link: <a href="my/path/to/link.html">My link</a></p>
```

----

Note: When using ``This is a link: `My link <//my/path/to/link.html>\`__`` as input, it does keep one forward slash in the output, but it seems like a workaround that should not be used.

Am I missing anything here?
Best regards,
PAC

**Comment by Gregwar** [comment]
Actually, this is my fault

I changed the behaviour so that urls begining with / are replaced with relative URL (see `Environment::relativeUrl`)

The goal of this is to avoid breaking link problems, like if you are in `/some/path` and reference an image in `/some/other/path/image.png` the resulting url will be `../other/path/image.png`

I agree that this could be an option

**Comment by pacproduct** [comment]
I understand your point. However I think that if this behavior could come in handy in some situations, it could also break some others as the whole point of using a URL starting with '/' is to make sure that the link will always point to this specific URL whatever the current path is.
So I agree with you: this should be an option.

I would even suggest that this should be turned off by default, IMHO :)

**Comment by Gregwar** [comment]
I added an option for that
You can do the following:

```php
$parser->getEnvironment()->setUseRelativeUrls(false);

// Or, if using the builder
$builder->setUseRelativeUrls(false)
```

Maybe I will change the default behaviour in the future, but I do not want to break BC now

**Comment by pacproduct** [comment]
Great reactivity, impressive!
I just tested your commit an it does solve the issue I was facing.

Many thanks!

----

I still think that the library should not try to guess too many things for "helping" users/contributors because it might guess things wrong sometimes.
I can think of a couple of situations where this "auto-relative URLs" behavior could be problematic:
- When source RST gets processed during a bulk conversion/migration operation: During such a conversion the current path is likely to be technical and not the final one.
- When preparing the cached version of a page for faster rendering later on: This conversion might happen in the background, not in the right context either, or within the site back-office (i.e. on a administration URL).

I believe that such a parser should be context independent by default. Ideally.
Just my opinion :)

Anyway keep up the good work.
Cheers.
