### ISSUE TITLE
Nested subdirectives broken

### ISSUE THREAD

**Issue by kieranmathieson** [Gregwar/RST#40]
Thanks for the parser. A useful thing!

I defined a dude subdirective. It's similar to the div code:

<pre><code>
namespace AppBundle\Service\RstCustomDirectives\Directives;

use Gregwar\RST\Parser;
use Gregwar\RST\SubDirective;
use Gregwar\RST\Nodes\WrapperNode;

class Dude extends SubDirective
{

    public function getName()
    {
        return 'dude';
    }

    public function processSub(Parser $parser, $document, $variable, $class, array $options)
    {
        $start = '&lt;div';
        if ($class) {
            $start .= ' class="'.$class.'"';
        }
        $start .= '>&lt;p>DUDE!&lt;/p>';
        return new WrapperNode($document, $start, '&lt;/div>');
    }
}
</code></pre>

Here's some test code:

<pre><code>        $rst = ' 
This is a **RST** document! About to div it.

.. div:: indent

    This is inside a div.

    .. div:: indent
    
        This is a nested div.
            
        .. div:: indent
    
            This is inside a nested div.

.. div:: indent

    This is a div after nested divs.

This is predude.

.. dude:: indent
    :scale: 50
    :weight: 68
    
    This is the first dude.
    
    .. dude:: indent
        :scale: 50
        :weight: 68

        This is your inner dude.

.. dude:: indent
    :scale: 50
    :weight: 68

    This is another dude.
        
This is post dude. AYE!
';
        $dudeDirective = new Dude();
        $parser = new Parser();
        $parser->registerDirective($dudeDirective);
        $document = $parser->parse($rst);
        return $this->render(':rst:rsttest.html.twig', [
            'base_dir' => realpath($this->getParameter('kernel.project_dir')).DIRECTORY_SEPARATOR,
            'parsedHtml' => $document,
        ]);
</code></pre>

There are divs in divs, and that works. When dudes are not nested in dudes, no problem. However, when a dude is nested in a dude, like the inner dude above, the code crashes. Error:

`Unknown directive: dude in (unknown) line 6`

The message seems to be from `$parser->getCurrentDirective()`.  `$parser->directives[]` doesn't contain dude at that point. However, dude was in `$parser->directives[]` earlier, when processing the first div. 

Not sure this is relevant: `SubDirective->process()` calls `$parser->getSubParser();` on line 24. That executes this line on Parser line 74:

`return new Parser($this->environment, $this->kernel)`

I don't see how the registered directives get passed there. Could that be the issue?

**Comment by Gregwar** [comment]
Hello,

How is your directive registered ?

You should do your own Kernel:

```php
<?php

use Gregwar\RST\Kernel;

class MyKernel extends Kernel
{
  public function getDirectives() {
    $directives = parent::getDirectives();
    $directives[] = new MyDirective;

    return $directives;
  }
}

$parser = new Parser(null, new MyKernel);

```php

**Comment by kieranmathieson** [comment]
That worked! Thank you!

The only change was...

`use Gregwar\RST\HTML\Kernel;`

... rather than...

`use Gregwar\RST\Kernel;`

... so that getName() was defined.

Thanks again for the parser. It's nice to have reStructuredText in the PHP world, and not have to settle for Markdown.
